name: Omri Mor - Product Designer
description: Online portfolio

url: 'http://localhost:4000'

paginate: 10

permalink: none
highlighter: rouge
exclude: [node_modules, Gruntfile.js, package.json, README.md, .gitignore, .jshintrc]

sass:
  sass_dir: _scss
  style: :compressed

gems: [jekyll-paginate]
