name: Omri Mor - Product Designer
description: My online shit

url: 'http://localhost:4000'

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
exclude: [node_modules, Gruntfile.js, package.json, README.md, .gitignore, .jshintrc]

sass:
  sass_dir: _scss
  style: :compressed
